trigger: none
pr: none
schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight smoke tests
  always: true
  branches:
    include:
    - master

pool: tasrif-pool

stages:
  - stage: Test
    jobs:
    - job: RunIpynbTests
      displayName: Run ipynb tests
      steps:
      - checkout: self
      - task: Docker@2
        displayName: Use Docker to run ipynb tests
        inputs:
          command: run
          containerRegistry: tasrif-acr
          # - Run ipynb tests on 'latest' Tasrif build.
          # - nbconvert prints html output to stdout and logging information to
          #   stderr. Redirect stderr to stdout and then redirect stdout to
          #   /dev/null.
          arguments: >- # '>-' is the 'block chomping indicator'
            --env PYTHONPATH=/home/ --entrypoint "/bin/bash"
            qcriswtasrif.azurecr.io/$(Build.Repository.Name):latest
            -c "jupyter nbconvert --to html --stdout
            --execute tasrif/test_scripts/test_pipeline_* 2>&1 > /dev/null"

