trigger: none
pr: none
schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight smoke tests
  always: true
  branches:
    include:
    - master

pool: tasrif-pool

stages:
  - stage: Test
    jobs:
    - job: RunIpynbTests
      displayName: Run ipynb tests
      steps:
      - checkout: self
      - task: Docker@2
        displayName: Use Docker to run ipynb tests
        inputs:
          command: run
          containerRegistry: tasrif-acr
          arguments: >- # '>-' is the 'block chomping indicator'
            --env PYTHONPATH=/home/ --entrypoint "/bin/bash"
            -v $(System.DefaultWorkingDirectory):/home/
            qcriswtasrif.azurecr.io/$(Build.Repository.Name):latest
            -c "pytest -v /home/tasrif/test_scripts/entrypoint.py --junitxml=/home/notebook-tests.xml"
      - task: PublishTestResults@2
        displayName: 'Publish pylint Results'
        inputs:
          testResultsFormat: 'Junit'
          testResultsFiles: '**/*.xml'
          searchFolder: '$(System.DefaultWorkingDirectory)'
          publishRunAttachments: true
          testRunTitle: 'Pylint'
        condition: succeededOrFailed()
