trigger:
  batch: true
  branches:
    include:
    - master
resources:
  - repo: self
# Builds can fail on self-hosted agents if they are not cleaned occasionally.
parameters:
- name: clean
  displayName: Checkout clean
  type: boolean
  default: false
  values:
  - false
  - true

pool: tasrif-pool

stages:
  - stage: Build
    jobs:
    - job: CheckChanges
      displayName: 'Check changes'
      steps:
        - script: |
            #!/bin/bash
            echo "##vso[task.setvariable variable=testvar;]testvalue"
            PATH_FILTER="tasrif/processing_pipeline/kats"
            CHANGED_FILES=$(git diff --name-only -- tasrif/processing_pipeline/kats/)

            for FILE in $CHANGED_FILES
            do
              PARENT_DIR=$(dirname ${FILE})
              if [[ $PARENT_DIR == *$PATH_FILTER* ]]; then
                echo "${FILE} changed"
                echo "##vso[task.setvariable variable=SOURCE_CODE_CHANGED;isOutput=true]true"
                exit 0
              fi
            done

            echo "##vso[task.setvariable variable=SOURCE_CODE_CHANGED;isOutput=true]false"
          name: check_changes
          displayName: 'Check changed files'

    - job: BuildTasrif
      displayName: Build Tasrif
      dependsOn: CheckChanges # <- Important: Mark previous job as dependency
      steps:
      - checkout: self
        clean: ${{ parameters.clean }}
      - task: Docker@2
        displayName: 'Build Tasrif'
        inputs:
          command: build
          repository: $(Build.Repository.Name)
          containerRegistry: tasrif-acr
          # Set tag to 'latest' only on builds from master branch
          ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
            tags: |
              $(Build.BuildId)
              latest
          ${{ if ne(variables['Build.SourceBranchName'], 'master') }}:
            tags: |
              $(Build.BuildId)
          arguments: --build-arg optional_code_changed=dependencies.CheckChanges.outputs['check_changes.SOURCE_CODE_CHANGED']

      - task: Docker@2
        displayName: 'Push Tasrif' 
        inputs:
          command: push
          repository: $(Build.Repository.Name)
          containerRegistry: tasrif-acr
          # Set tag to 'latest' only on builds from master branch
          ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
            tags: |
              $(Build.BuildId)
              latest
          ${{ if ne(variables['Build.SourceBranchName'], 'master') }}:
            tags: |
              $(Build.BuildId)

  - stage: Test
    jobs:
    - job: RunPylint
      displayName: Run pylint
      steps:
      - checkout: none # No need, docker run will pull the image
      - task: Docker@2
        displayName: 'Run pylint'
        inputs:
          command: run # Docker@2 can take direct docker commands as input
          containerRegistry: tasrif-acr
          arguments: >-
            -v $(System.DefaultWorkingDirectory)/pylint:/home/pylint
            qcriswtasrif.azurecr.io/$(Build.Repository.Name):$(Build.BuildId)
            /home/run-pylint.sh
      - task: PublishTestResults@2
        displayName: 'Publish pylint results'
        inputs:
          testResultsFormat: 'Junit'
          testResultsFiles: '**/*.xml'
          searchFolder: '$(System.DefaultWorkingDirectory)/pylint'
          publishRunAttachments: true
          testRunTitle: 'Pylint'
        condition: succeededOrFailed()
    - job: RunUnitTests
      displayName: Run unit tests
      steps:
        # Checkout the repo here so that references to the source files in
        # the coverage results are correctly linked.
      - checkout: self
      - task: Docker@2
        displayName: Use Docker to run unit tests
        inputs:
          command: run
          containerRegistry: tasrif-acr
          arguments: >-
            --env PYTHONPATH=/home/ --entrypoint "/bin/bash"
            -v $(System.DefaultWorkingDirectory):/home/
            qcriswtasrif.azurecr.io/$(Build.Repository.Name):$(Build.BuildId)
            -c "pytest -v --ignore=/home/tasrif/test_scripts
            --cov=tasrif --cov-report=xml --junitxml=/home/unit-tests.xml
      - task: PublishTestResults@2
        displayName: 'Publish unit tests results'
        inputs:
          testResultsFormat: 'Junit'
          testResultsFiles: '**/unit-tests.xml'
          searchFolder: '$(System.DefaultWorkingDirectory)'
          publishRunAttachments: true
          testRunTitle: 'Unit tests'
        condition: succeededOrFailed()
      - task: UseDotNet@2
        displayName: 'Use .NET Core sdk'
        inputs:
          packageType: sdk
          version: 2.2.203
          installationPath: $(Agent.ToolsDirectory)/dotnet
      - task: PublishCodeCoverageResults@1
        displayName: 'Publish coverage report'
        inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
          pathToSources: $(Build.SourcesDirectory)
    - job: RunNotebookTests
      displayName: Run notebook tests
      steps:
      - checkout: none
      - task: Docker@2
        displayName: Use Docker to run notebook tests
        inputs:
          command: run
          containerRegistry: tasrif-acr
          arguments: >-
            --env PYTHONPATH=/home/ --entrypoint "/bin/bash"
            -v $(System.DefaultWorkingDirectory):/home/
            qcriswtasrif.azurecr.io/$(Build.Repository.Name):$(Build.BuildId)
            -c "pytest -v /home/tasrif/test_scripts/entrypoint.py
            --junitxml=/home/notebook-tests.xml"
      - task: PublishTestResults@2
        displayName: 'Publish notebook tests results'
        inputs:
          testResultsFormat: 'Junit'
          testResultsFiles: '**/notebook-tests.xml'
          searchFolder: '$(System.DefaultWorkingDirectory)'
          publishRunAttachments: true
          testRunTitle: 'Notebook tests'
        condition: succeededOrFailed()
    - job: RunDarglint
      displayName: Run darglint
      steps:
      - checkout: none # No need, docker run will pull the image
      - task: Docker@2
        displayName: 'Run darglint'
        inputs:
          command: run # Docker@2 can take direct docker commands as input
          containerRegistry: tasrif-acr
          arguments: >-
            -v $(System.DefaultWorkingDirectory)/darglint:/home/darglint
            qcriswtasrif.azurecr.io/$(Build.Repository.Name):$(Build.BuildId)
            /home/run-darglint.sh
      - task: PublishTestResults@2
        displayName: 'Publish darglint results'
        inputs:
          testResultsFormat: 'Junit'
          testResultsFiles: '**/*.xml'
          searchFolder: '$(System.DefaultWorkingDirectory)/darglint'
          publishRunAttachments: true
          testRunTitle: 'Darglint'
        condition: succeededOrFailed()

