trigger:
  batch: true
  branches:
    include:
    - master
resources:
  - repo: self

pool:
  name: tasrif-pool
  demands:
    # This is key to schedule the jobs on the agent with datafabric access.
    - datafabric

jobs:
  - job: RunNotebookTests
    displayName: Run Notebook Tests
    steps:
      - checkout: self
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.7'
      - bash: |
          export FITBIT_INTERDAY_PATH=
          export FITBIT_INTRADAY_PATH=
          export MYHEARTCOUNTS_ACTIVITYSLEEPSURVEY_PATH='/export/qcai-healthdata01/MyHeartCounts/Activity and Sleep Survey.csv'
          export MYHEARTCOUNTS_CARDIODIETSURVEY_PATH='/export/qcai-healthdata01/MyHeartCounts/Cardio Diet Survey.csv'
          export MYHEARTCOUNTS_DAILYCHECKSURVEY_PATH='/export/qcai-healthdata01/MyHeartCounts/Daily Check Survey.csv'
          export MYHEARTCOUNTS_DAYONESURVEY_PATH='/export/qcai-healthdata01/MyHeartCounts/Day One Survey.csv'
          export MYHEARTCOUNTS_DEMOGRAPHICS_PATH='/export/qcai-healthdata01/MyHeartCounts/Demographics Survey.csv'
          export MYHEARTCOUNTS_HEALTHKITDATA_CSV_FOLDER_PATH='/export/qcai-healthdata01/MyHeartCounts/HealthKit Data'
          export MYHEARTCOUNTS_HEALTHKITDATA_PATH='/export/qcai-healthdata01/MyHeartCounts/HealthKit Data.csv'
          export MYHEARTCOUNTS_HEALTHKITSLEEP_CSV_FOLDER_PATH='/export/qcai-healthdata01/MyHeartCounts/HealthKit Sleep'
          export MYHEARTCOUNTS_HEALTHKITSLEEP_PATH='/export/qcai-healthdata01/MyHeartCounts/HealthKit Sleep.csv'
          export MYHEARTCOUNTS_HEARTAGESURVEY_PATH='/export/qcai-healthdata01/MyHeartCounts/APH Heart Age Survey.csv'
          export MYHEARTCOUNTS_PARQSURVEY_PATH='/export/qcai-healthdata01/MyHeartCounts/PAR-Q Survey.csv'
          export MYHEARTCOUNTS_QUALITYOFLIFE_PATH='/export/qcai-healthdata01/MyHeartCounts/Satisfied Survey.csv'
          export MYHEARTCOUNTS_RISKFACTORSURVEY_PATH='/export/qcai-healthdata01/MyHeartCounts/Risk Factor Survey.csv'
          export MYHEARTCOUNTS_SIXMINUTEWALKACTIVITY_JSON_FOLDER_PATH='/export/qcai-healthdata01/MyHeartCounts/Six Minute Walk Activity'
          export MYHEARTCOUNTS_SIXMINUTEWALKACTIVITY_PATH='/export/qcai-healthdata01/MyHeartCounts/Six Minute Walk Activity.csv'
          export SIHA_PATH=
          export SLEEPHEALTH_ABOUTME_PATH='/export/qcai-healthdata01/sleephealth/About Me.csv'
          export SLEEPHEALTH_AMCHECKIN_PATH='/export/qcai-healthdata01/sleephealth/AM Check-in.csv'
          export SLEEPHEALTH_MYFAMILY_PATH='/export/qcai-healthdata01/sleephealth/My Family.csv'
          export SLEEPHEALTH_MYHEALTH_PATH='/export/qcai-healthdata01/sleephealth/My Health.csv'
          export SLEEPHEALTH_ONBOARDINGDEMOGRAPHICS_PATH='/export/qcai-healthdata01/sleephealth/Onboarding Demographics.csv'
          export SLEEPHEALTH_PMCHECKIN_PATH='/export/qcai-healthdata01/sleephealth/PM Check-in.csv'
          export SLEEPHEALTH_RESEARCHINTEREST_PATH='/export/qcai-healthdata01/sleephealth/Research Interest.csv'
          export SLEEPHEALTH_SLEEPASSESSMENT_PATH='/export/qcai-healthdata01/sleephealth/Sleep Assessment.csv'
          export SLEEPHEALTH_SLEEPHABIT_PATH='/export/qcai-healthdata01/sleephealth/Sleep Habits.csv'
          export SLEEPHEALTH_SLEEPQUALITYCHECKER_PATH='/export/qcai-healthdata01/sleephealth/Sleep Quality Checker.csv'
          export WITHINGS_PATH=
          export ZENODOFITBIT_PATH=/export/qcai-healthdata01/Zenodo_Fitbit

          export PYTHONPATH=$(System.DefaultWorkingDirectory)
          python3.7 -m venv env
          source env/bin/activate
          pip3.7 install --upgrade pip
          pip3.7 install -r qa-requirements.txt
          pip3.7 install -r requirements.txt
          MINIMAL=1 pip3.7 install -e .
          pytest -v tasrif/test_scripts/entrypoint.py --junitxml=notebook-tests.xml
        displayName: 'Install deps and run tests'
      - task: PublishTestResults@2
        displayName: 'Publish notebook tests results'
        inputs:
          testResultsFormat: 'Junit'
          testResultsFiles: 'notebook-tests.xml'
          searchFolder: '$(System.DefaultWorkingDirectory)'
          publishRunAttachments: true
          testRunTitle: 'Notebook tests'
        condition: succeededOrFailed()
